export const FETCH_GENERATION_LIST = 'FETCH_GENERATION_LIST';
export const DELETE_GENERATION_LIST = 'DELETE_GENERATION_LIST';
export const FETCH_AGENT_LIST = 'FETCH_AGENT_LIST';
export const DELETE_AGENT_LIST = 'DELETE_AGENT_LIST';
export const ADD_GAME = 'ADD_GAME';
export const SET_ALERT = 'SET_ALERT';